name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

 #     - name: Run Terraform RG, ACR and NETWORK
 #       run: |
 #         cd terraform
 #         terraform init
 #         terraform apply -target=module.rg -auto-approve
 #         terraform apply -target=module.acr -auto-approve
 #         terraform apply -target=module.network -auto-approve

 #     - name: Build and push Docker image
 #       run: |
 #         ./deployment/build_push.sh

      - name: Run Terraform AKS
        run: |
          cd terraform
          terraform init
          terraform apply -target=module.aks -auto-approve
