name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: "ad73cf00-da95-4fd4-8183-f00a635c1a30"
          tenant-id: "3abc5e4e-1080-4991-a58f-815a337e150b"
          subscription-id: "41baa1e3-240b-4ac6-9767-ebff98622ea2"

      - name: Build and push Docker image
        run: |
          ./deployment/build_push.sh

      - name: Run Terraform
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
